apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  sector:
    app: php
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer

---

apiVersion: v1kind: Servicemetadata:
  name: mysql-connection
spec:
  ports:
  - port: mysql-connection
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None  